language: go
go:
  - tip
before_install:
- go get -d github.com/mattcunningham/haas-hall-lottery

install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

script:
- go test -v ./...
- $HOME/gopath/bin/goveralls  -service=travis-ci